### ISSUE TITLE
API questions

### ISSUE THREAD

**Issue by ghost** [jeehoonkang/membarrier-rs#13]
1. Now that we have a fallback for `sys_membarrier()`, is there any reason for keeping the `linux_membarrier` feature?

2. Is there any purpose to the `Membarrier` struct? Why not simply have three global functions named `fast_path`, `normal_path`, and `slow_path`?

Alternatively, we could have the following module structure:

```rust
// These call the most appropriate functions.
fn fast_path();
fn normal_path();
fn slow_path();

// Available on all platforms.
mod default {
    fn fast_path();
    fn normal_path();
    fn slow_path();
}

#[cfg(target_os = "linux")]
mod linux {
    fn fast_path();
    fn normal_path();
    fn slow_path();
}

#[cfg(target_os = "windows")]
mod windows {
    fn fast_path();
    fn normal_path();
    fn slow_path();
}
```

**Comment by jeehoonkang** [comment]
I agree with both of your points.  The motivation behind struct was avoiding an access to `lazy_static!` variable in `*_path()` functions.  But it turns out that it's accessed only in `slow_path()`, which can be, um, slow :)

Furthermore, I'm not 100% happy with the function names.  I'm thinking of the following alternatives:

- `weak()`, `normal()`, and `strong()`: I prefer it most because it describes the behavior, not performance characteristics.
- `fast()`, `normal()`, and `slow()`: because "path" doesn't give you much information in this case.

**Comment by ghost** [comment]
In Folly, these barriers are called "light" and "heavy".
Not sure which naming works best, I'll have to think about it...

By the way, do we need to include the "normal" barrier since it's always just a synonym for a `SeqCst` fence?

**Comment by jeehoonkang** [comment]
- I like `light` and `heavy` :)
- on `normal`: yeah, I agree with you.  It's enough to document that a `SeqCst` fence and a heavy fence are synchronizing with each other.
